name: Build TankExporter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # Сборка на Windows
    strategy:
      matrix:
        platform: [ x86 ]   # Только x86

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Установка vcpkg и зависимостей
    - name: Setup dependencies (vcpkg)
      run: |
        git clone https://github.com/microsoft/vcpkg
        ./vcpkg/bootstrap-vcpkg.bat
        ./vcpkg/vcpkg install glew:x86-windows

    # Скачивание FBX SDK (пример, замените на реальный URL)
    - name: Download FBX SDK
      run: |
        $url = "https://github.com/metarutaiga/FBXSDK/blob/master/lib/vs2015/x86/release/libfbxsdk.dll"  # Замените на реальный URL
        Invoke-WebRequest -Uri $url -OutFile fbxsdk.zip
        7z x fbxsdk.zip -o"C:\FBX_SDK"

    # Настройка переменных окружения для FBX SDK
    - name: Configure FBX SDK
      shell: pwsh
      run: |
        echo "FBX_SDK_INCLUDE=C:\FBX_SDK\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "FBX_SDK_LIB=C:\FBX_SDK\lib\vs2019\x86\release" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # Сборка решения
    - name: Build Solution
      shell: pwsh
      run: |
        msbuild TankExporter.sln `
          /p:Configuration=Release `
          /p:Platform="x86" `
          /p:PlatformToolset=v143 `
          /p:VcpkgEnabled=true `
          /p:VcpkgTriplet=x86-windows `
          /p:AdditionalIncludeDirectories="$env:FBX_SDK_INCLUDE" `
          /p:AdditionalLibraryDirectories="$env:FBX_SDK_LIB"

    # Копирование DLL в артефакты
    - name: Collect Artifacts
      shell: pwsh
      run: |
        mkdir artifacts
        copy "bin\x86\Release\*.exe" artifacts
        copy "bin\x86\Release\*.dll" artifacts
        copy "C:\vcpkg\installed\x86-windows\bin\*.dll" artifacts
        copy "C:\FBX_SDK\lib\vs2019\x86\release\*.dll" artifacts

    # Публикация артефактов
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TankExporter-Build
        path: artifacts
